/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.view;

import br.edu.ifrn.model.Contato;
import static br.edu.ifrn.model.Contato.ler;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Max Martins
 */
public class TelaPrincipalADMIN extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalADMIN
     */
    public TelaPrincipalADMIN() {
        initComponents();
        this.setLocationRelativeTo(null);
        preencherTabela();
    }
    
    public void preencherTabela() {
        String ddContatos = "Contatos.txt";
        File dd = new File(ddContatos);
        
        try{
            FileReader ddc = new FileReader(dd);
            BufferedReader bfrd = new BufferedReader(ddc);
            DefaultTableModel dtmModel = (DefaultTableModel)tblDados.getModel();
            Object[] dados = bfrd.lines().toArray();
            
            for (int i = 0; i < dados.length; i++){
                String[] linha = dados[i].toString().split(",");
                dtmModel.addRow(linha);
        }
            
        } catch(FileNotFoundException ex){
            ex.getMessage();
        }
    }
    public void limparDados(){
        txtNome.setText("");
        txtEndereço.setText("");
        txtfNascimento.setText("");
        txtfTelFixo.setText("");
        txtfCelular.setText("");
        cbxTurma.setSelectedIndex(0);
    }
    public void adicionar() throws IOException {
        Contato c = new Contato();
        
        
        if (txtNome.getText().equals("") || txtEndereço.getText().equals("") || 
                txtfNascimento.getText().equals("") || cbxTurma.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, " Preencha os campos obrigatórios ", " Error", JOptionPane.ERROR_MESSAGE);
        } else {
            c.setNome(txtNome.getText());
            c.setEndereco(txtEndereço.getText());
            c.setNascimento(txtfNascimento.getText());
            c.setTelFixo(txtfTelFixo.getText());
            c.setCelular(txtfCelular.getText());
            c.setTurma(cbxTurma.getSelectedItem().toString());
            Contato contatos = new Contato();
            contatos.addContato(c);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso! ", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
        }
        limparDados();
        
    }
    
    public boolean atualizar (){
        if(tblDados.getSelectedRow() != -1){
            
            tblDados.setValueAt(txtNome.getText(),tblDados.getSelectedRow(),0);
            tblDados.setValueAt(txtEndereço.getText(),tblDados.getSelectedRow(),1);
            tblDados.setValueAt(txtfNascimento.getText(),tblDados.getSelectedRow(),2);
            tblDados.setValueAt(txtfTelFixo.getText(),tblDados.getSelectedRow(),3);
            tblDados.setValueAt(txtfCelular.getText(),tblDados.getSelectedRow(),4);
            tblDados.setValueAt(cbxTurma.getSelectedItem(),tblDados.getSelectedRow(),5);
           return true;
        }else{
            return false;
        }
     }
    public void deletar() throws IOException {
        String ddContatos = "Contatos.txt";
        File arq = new File(ddContatos);
        BufferedWriter bfWrite = new BufferedWriter(new FileWriter(arq.getPath()));
        
        for(int ln = 0; ln < tblDados.getRowCount(); ln++){
           for(int cl = 0; cl < tblDados.getColumnCount(); cl++){
               bfWrite.write(tblDados.getValueAt(ln, cl).toString()+",");
           }
           bfWrite.write("\n");
        }
        bfWrite.flush();
        bfWrite.close();
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEndereço = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereço = new javax.swing.JTextField();
        txtfNascimento = new javax.swing.JFormattedTextField();
        lblTelFixo = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblTurma = new javax.swing.JLabel();
        txtfTelFixo = new javax.swing.JFormattedTextField();
        txtfCelular = new javax.swing.JFormattedTextField();
        cbxTurma = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblEndereço.setText("Endereço:");

        lblNascimento.setText("Data de Nascimento:");

        try {
            txtfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblTelFixo.setText("Tel. Fixo:");

        lblCelular.setText("Celular:");

        lblTurma.setText("Turma:");

        try {
            txtfTelFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbxTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADS", "Química", "Informática", "Alimentos" }));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblPesquisar.setText("Pesquisar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtfTelFixo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(lblNome)
                        .addComponent(txtNome)
                        .addComponent(lblTelFixo))
                    .addComponent(btnCadastrar))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblEndereço)
                        .addComponent(txtEndereço)
                        .addComponent(lblCelular)
                        .addComponent(txtfCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(lblPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfNascimento)
                    .addComponent(lblTurma)
                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa))
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblEndereço)
                    .addComponent(lblNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelFixo)
                    .addComponent(lblCelular)
                    .addComponent(lblTurma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAtualizar)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Endereço", "Data de Nascimento", "Tel. Fixo", "Celular", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDadosMouseClicked(evt);
            }
        });
        tblDados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        DefaultTableModel dtmDados = (DefaultTableModel) tblDados.getModel();
        Object[] tDados = {txtNome.getText(),txtEndereço.getText(),txtfNascimento.getText(),
                           txtfTelFixo.getText(),txtfCelular.getText(),cbxTurma.getSelectedItem().toString()};
        dtmDados.addRow(tDados);
        try {
            // TODO add your handling code here:
            adicionar();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipalADMIN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
            atualizar();
            try {
                
                deletar();
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipalADMIN.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tblDadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDadosKeyReleased
        // TODO add your handling code here:
        try{
            if(tblDados.getSelectedRow() != -1){
                txtNome.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 0).toString());
                //txtNome.disable();
                txtEndereço.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 1).toString());
                txtfNascimento.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 2).toString());
                txtfTelFixo.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 3).toString());
                txtfCelular.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 4).toString());
                cbxTurma.setSelectedItem((int) tblDados.getValueAt(tblDados.getSelectedRow(), 5));
            }
            
        }catch (ClassCastException ex){
            ex.getMessage();
        }
    }//GEN-LAST:event_tblDadosKeyReleased

    private void tblDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDadosMouseClicked
        // TODO add your handling code here:
        try{
            if(tblDados.getSelectedRow() != -1){
                txtNome.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 0).toString());
                txtNome.disable();
                txtEndereço.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 1).toString());
                txtfNascimento.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 2).toString());
                txtfTelFixo.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 3).toString());
                txtfCelular.setText(tblDados.getValueAt(tblDados.getSelectedRow(), 4).toString());
                cbxTurma.setSelectedItem((int) tblDados.getValueAt(tblDados.getSelectedRow(), 5));
            }
                
        }catch (ClassCastException ex){
            ex.getMessage();
            
        }
        
    }//GEN-LAST:event_tblDadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cbxTurma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEndereço;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTelFixo;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtEndereço;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JFormattedTextField txtfCelular;
    private javax.swing.JFormattedTextField txtfNascimento;
    private javax.swing.JFormattedTextField txtfTelFixo;
    // End of variables declaration//GEN-END:variables
}
